# Site
repository: jiwon1027/resume
favicon: images/favicon.ico

# Personal info
name: 이지원 (Lee Ji won)
title: Back-End Developer
email: won64312000@naver.com
website: https://ddangjiwon1027.tistory.com
phone: 010 - 6429 - 1037
# Social links
github_username: jiwon1027
# dribbble_username: jekyll
# facebook_username: won64312000
# flickr_username: jekyll
# instagram_username:
# linkedin_username:
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  나이 : 26 세 (1997년 생)

  최종 학력 : 동의대학교 컴퓨터공학 졸업

  사는 곳 : 서울특별시 중랑구

  병역 : 2018.02 ~ 2019.10 육군 병장 만기제대

  사용 기술 : <mark>Python</mark> <mark>Django</mark> <mark>MySQL</mark>



# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# test Section
# test_title: test

# More Section
#more_title: Other
#more_content: | # this will include new lines to allow paragraphs
#  - [개인 블로그](https://ddangjiwon1027.tistory.com/)

# Footer
footer_show_references: true

# Build settings
livereload: true

remote_theme: jiwon1027/resume

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
