# Site
repository: jiwon1027/resume
favicon: images/favicon.ico

# Personal info
name: 이지원 (Lee Ji won)
title: 데이터 분석과 인프라 구축 능력을 겸비한 Back-End Developer
email: won64312000@naver.com
website: https://ddangjiwon.tistory.com
phone: 010 - 6429 - 1037
# Social links
github_username: jiwon1027
# dribbble_username: jekyll
# facebook_username: won64312000
# flickr_username: jekyll
# instagram_username:
# linkedin_username:
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  **팀 활동과 코드 퀄리티를 중요시 생각하는 신입 백엔드 개발자 이지원 입니다.**
  <br>

  - 새로운 기술 스택에 관심이 많고 배우는 것과 기록하는 걸 좋아합니다.

  - 기술 구현을 넘어서 OOP 및 인프라에도 관심이 있습니다.

  - 반복되는 일을 자동화하고 비효율적인 프로세스를 개선하는 일을 좋아합니다.

  - 적극적으로 의견을 내고 해야할 일을 스스로 찾는 개발자 입니다.



# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# test Section
# test_title: test

# More Section
#more_title: Other
#more_content: | # this will include new lines to allow paragraphs
#  - [개인 블로그](https://ddangjiwon.tistory.com/)

# Footer
footer_show_references: true

# Build settings
livereload: true

remote_theme: jiwon1027/resume

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
