# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이지원 (Lee Ji Won)
title: Back-End Developer
email: won64312000@naver.com
# email_title: Email (Email title override)
phone: 010 - 6429 - 1037
# phone_title: Phone (Phone title override)
website: https://ddangjiwon.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jiwon1027

# Additional icon links
additional_links:
- title: Personal Blog
  icon: fa-solid fa-cube
  url: https://ddangjiwon.tistory.com

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  나이 : 26세(1997년생)

  최종 학력 : 동의대학교 컴퓨터공학 졸업(3.84 / 4.5)

  사는 곳 : 서울특별시 중랑구

  병역 : 2018.02 ~ 2019.10 육군 병장 만기제대

  보유기술 : <mark>Python</mark> <mark>Django</mark> <mark>MySQL</mark>


  나는 문어
    - 꿈을 꾸는 문어
    - 꿈속에서는 무엇이든지 될 수 있어
    - <a href="google.com">나는 문어</a>
    - 문어 ![alt text](/images/oc.jpg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
